### ISSUE TITLE
ModuleNotFoundError: No module named 'openchecks.openchecks

### ISSUE THREAD

**Issue by aditiapratama** [scott-wilson/openchecks#286]
Hello Scott,

I tried to import module from wheel package but I got following error
```shell
Traceback (most recent call last):
  File "/home/aditia/Documents/production_tools/openchecks/import_test/test.py", line 27, in <module>
    module = importlib.import_module(module_name)
  File "/home/aditia/.pyenv/versions/3.10.14/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/aditia/Documents/production_tools/openchecks/import_test/openchecks-0.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl/openchecks/__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'openchecks.openchecks
```
Here you can download the zip,
[import_test.zip](https://github.com/user-attachments/files/16522207/import_test.zip)

and here's the step to generate the error:
1. `cd import_test`
2. `python test.py`

**Comment by scott-wilson** [comment]
How did you install the wheel? I have found that `pip install openchecks` works. But, I'll take a look at your test case shortly.

**Comment by scott-wilson** [comment]
That may be the reason. I did a quick look, and `pip wheel` looks like it only builds wheels, but I believe you can do `pip install /path/to/openchecks-0.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`.

You might need to do it in a virtual environment, so you can do the following steps: 

1. `python3 -m venv .venv`
2. `source .venv/bin/activate`
3. `python -m pip install openchecks`

But, if you're trying to build it, then that's slightly different. I will have to update the readme to make sure that's in there (excuse the mess).

**Comment by aditiapratama** [comment]
ah ok thanks Scott, by the way the reason i use that way is I tried to bundle it in Blender Extension, so it seems I need to call pip install through blender python?

**Comment by scott-wilson** [comment]
Yeah, there's a few ways you could get it to work. Doing the pip install may work, or you might need to vendor it manually. I'll be interested in hearing what you do, though.

**Comment by aditiapratama** [comment]
yeah probably manually vendor is not bad idea, I also notice pip wheel will provide linux only `.so` file...so probably need to use os detection as well to install in user pc...I'll update again later, Thank you so much Scott.

**Comment by scott-wilson** [comment]
I'm going to close this ticket for now, since it seems that the original issue is resolved. However, feel free to open a new ticket or post in the discussions.

**Comment by aditiapratama** [comment]
Yes, no worries...in the end I created function to pip install openchecks on addon register. Thanks
